Занятие 5: Обработчики событий
js-tasks-ru/jsbasic-20200727_aleksandr104 pull request #6
Opened 2020-08-19 11:04 UTC by alexti86

Последнему заданию попробовал сделать без учета фиксированного количества слайдов, поэтому получилось сложнее и возможно некрасивее:)

2020-08-19 11:11 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Спрятать себя
+ после клика по кнопке она должна исчезнуть
```
```diff
Учебный проект (пролог): Карусель
+ при клике по кнопке "назад", должна переключать на один слайд назад
+ должна по умолчанию скрыть стрелку переключения назад
+ при достижении четвёртого слайда, должна скрыть стрелку переключения вперёд
+ при клике по кнопке "вперёд", должна переключать на один слайд вперёд
```
```diff
Скрыть элемент по нажатию кнопки
+ после первого клика по кнопке текст должен исчезнуть
+ после повторного клика по кнопке текст должен появиться
```

Добавляю преподавателя (@stas-dolgachov) для код-ревью, посмотрим что он скажет :)

2020-08-19 18:07 UTC, stas-dolgachov requested changes

2020-08-19 18:07 UTC, stas-dolgachov commented on 5-module/1-task/index.js
> +  button = document.querySelector('.hide-self-button');
👍

2020-08-19 18:07 UTC, stas-dolgachov commented on 5-module/2-task/index.js
> +  div = document.getElementById('text');
👍

2020-08-19 18:07 UTC, stas-dolgachov commented on 5-module/3-task/index.js
> +  carousel = document.querySelector('.carousel__inner');
Переменные всегда нужно объявлять, иначе они создаются как глобальные. Добавьте здесь, пожалуйста, let или const

2020-08-19 18:07 UTC, stas-dolgachov commented on 5-module/3-task/index.js
> +  buttons = document.querySelectorAll('.carousel__arrow');
Переменные всегда нужно объявлять, иначе они создаются как глобальные. Добавьте здесь, пожалуйста, let или const

2020-08-19 18:07 UTC, stas-dolgachov commented on 5-module/3-task/index.js
> +function displayArrow(countCarousel, carouselLength) {
Отлично, что вынесли отдельную функцию!

2020-08-19 18:07 UTC, stas-dolgachov commented on 5-module/3-task/index.js
> +    if ((countCarousel == 0 && classButton== 'carousel__arrow_left')
Условие 
```
(countCarousel == 0 && classButton== 'carousel__arrow_left')
      || (Math.abs(countCarousel) == carouselLength - 1
        && classButton == 'carousel__arrow_right')
```
Слишком большое и длинное. Рекомендую разбить его на переменные или вынести все значение в одну переменную с понятным названием. 

```
let isFirstSlide = countCarousel == 0 && classButton== 'carousel__arrow_left';
let isLastSlide = (Math.abs(countCarousel) == carouselLength - 1
        && classButton == 'carousel__arrow_right');

if (isFirstSlide || isLastSlide) { ... }
```

2020-08-19 18:07 UTC, stas-dolgachov commented on 5-module/3-task/index.js
> +      || (Math.abs(countCarousel) == carouselLength - 1
А зачем здесь Math.abs?

2020-08-19 20:31 UTC, alexti86 commented on 5-module/3-task/index.js
> +  carousel = document.querySelector('.carousel__inner');
Принято

2020-08-19 20:32 UTC, alexti86 commented on 5-module/3-task/index.js
> +  buttons = document.querySelectorAll('.carousel__arrow');
Принято

2020-08-19 20:32 UTC, alexti86 commented on 5-module/3-task/index.js
> +    if ((countCarousel == 0 && classButton== 'carousel__arrow_left')
Разумно:)

2020-08-19 20:35 UTC, alexti86 commented on 5-module/3-task/index.js
> +      || (Math.abs(countCarousel) == carouselLength - 1
countCarousel уйдет в минус при прокрутке вправо, поэтому беру число по модулю.

2020-08-20 07:08 UTC, jsru commented
@stas-dolgachov ping :)

2020-08-20 11:24 UTC, stas-dolgachov approved these changes
Спасибо, что учли мои комментарии!

2020-08-20 11:24 UTC, merged