Занятие 7: Сложные компоненты
js-tasks-ru/jsbasic-20200727_aleksandr104 pull request #8
Opened 2020-08-27 13:20 UTC by alexti86

2020-08-27 13:27 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Учебный проект: Модальное окно
+ должен задавать заголовок модального окна
+ должен вставлять содержимое модального окна в элемента с классом "modal__body"
+ при нажатии клавиши ESC, вёрстка модального окна должна удаляться из body
+ при нажатии клавиши ESC, должен удаляться класс "is-modal-open" с элемента body
+ при клике по [X], должен удаляться кл��сс "is-modal-open" с элемента body
+ при вызове метода close(), вёрстка модального окна должна удаляться из body
+ при клике по [X], вёрстка модального окна должна удаляться из body
+ при вызове метода close(), должен удаляться класс "is-modal-open" с элемента body
+ должна создавать основной элемент модального окна
+ должна создавать прозрачный фон
+ должна добавлять класс "is-modal-open" элементу body
```
```diff
Учебный проект: Пошаговый слайдер, часть 2
+ должен перемещать ползунок
+ должен задавать ширину закрашиваемой области до ползунка
+ должен генерировать событие изменения значения
+ должен генерировать событие изменения значения
+ должен задавать закрашиваемую область до ползунка
+ должен добавлять класс slider_dragging
+ должен перемещать ползунок после захвата и перемещения
+ после создания должно быть нарисовано количество шагов переданное в момент создания
+ первый шаг должен быть активным
```
```diff
Учебный проект: Пошаговый слайдер, часть 1
+ после создания должно быть нарисовано количество шагов, переданное в момент создания
+ первый шаг должен быть активным
+ должен генерировать событие изменения значения
+ должен перемещать ползунок
+ должен задавать ширину закрашиваемой области до ползунка
```
```diff
Учебный проект: Лента-Меню
+ созданное событие должно содержать в себе уникальный идентификатор товара ("id")
+ после клика по ссылке, должно быть создано событие
+ должна добавлять корневой элемент в свойство "elem"
+ должна отрисовать все категории
+ при клике на кнопке "вперёд", должна прокрутить на 350px вперёд
+ при клике по кнопке "назад", должна прокрутить на 350px назад
```

Добавляю преподавателя (@stas-dolgachov) для код-ревью, посмотрим что он скажет :)

2020-08-28 08:38 UTC, stas-dolgachov requested changes
Отличные решения задач! Посмотрите, пожалуйста, мои комментарии

2020-08-28 08:38 UTC, stas-dolgachov commented on 7-module/1-task/index.js
> +    let innerHtml = '<button class="ribbon__arrow ribbon__arrow_left">';
Здесь можно попробовать использовать обратные кавычки и многострочную строку для присвоения. Вот так:
```
let innerHTML = `
<button class="ribbon__arrow ribbon__arrow_left">
  <img src="/assets/images/icons/angle-icon.svg" alt="icon">
</button>
`

```

2020-08-28 08:38 UTC, stas-dolgachov commented on 7-module/1-task/index.js
> +      if (isFirstSlide || isLastSlide) {
👍

2020-08-28 08:38 UTC, stas-dolgachov commented on 7-module/2-task/index.js
> +    document.body.addEventListener('keydown', () => {
Этот обработчик нужно удалять, после того, как модальное окно закрывается.

2020-08-28 08:38 UTC, stas-dolgachov commented on 7-module/3-task/index.js
> +    let ActiveStep = document.querySelector('.slider__step-active');
Именование переменных с большой буквы обычно используется для классов. Здесь все-таки лучше именовать с маленькой.

2020-08-28 08:38 UTC, stas-dolgachov commented on 7-module/3-task/index.js
> +    let thumb = document.querySelector('.slider__thumb');
Эти два элемента можно найти в самом начале и сохранить в свойства. Чтобы не искать каждый раз. Только искать их нужно будет внутри корневого элемента, а не всего документа.

2020-08-28 08:38 UTC, stas-dolgachov commented on 7-module/4-task/index.js
> +    let slider = document.querySelector('.slider');
Элемент слайдера у вас должен быть сохранен в свойстве elem. Вам нет необходимости его искать здесь

2020-08-28 08:38 UTC, stas-dolgachov commented on 7-module/4-task/index.js
> +    let divSliderValue = document.querySelector('.slider__value');
В целом я рекомендую искать все внутри самого элемента слайдера. Вам не необходимости искать по всему документу.

2020-08-28 11:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @stas-dolgachov

2020-08-30 09:52 UTC, stas-dolgachov approved these changes

2020-08-30 09:52 UTC, merged